authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
name = "Millboard"
uuid = "39ec1447-df44-5f4c-beaa-866f30b4d3b2"
version = "0.3.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
